---
- hosts: master1.levvel.internal
  tasks:
    - name: Login to OpenShift
      command: oc login https://ec2-52-207-89-9.compute-1.amazonaws.com:8443 -u admin

    - name: Get the Project names
      command: bash -c "oc get project | awk '{print $1}' | sed 's/\(openshift\s*\|openshift-infra\s*\|management-infra\s*\|logging\s*\|default\s*\|kube-system\s*\|testing\s*\|is-test\s*\|NAME\)//g' | sed '/^$/d;s/[[:blank:]]//g'"
      register: myoutput

    - name: Test message
      debug:
        msg: "{{myoutput}}"

    - name: Iterate for project (replace name later)
      include: "./tasks/oc_backup.yml"
      with_items: "{{ myoutput.stdout_lines }}"
