---
- hosts: master1.levvel.internal
  vars_prompt:
    - name: "oc_hostname"
      prompt: "Enter your OC hostname:"
    - name: "oc_user"
      prompt: "Username:"
    - name: "oc_password"
      prompt: "Password:"

  tasks:
    - name: Login to OpenShift
      command: bash -c "oc login {{oc_hostname}} -u {{oc_user}} -p {{oc_password}}"

    - name: Get the Project names
      command: bash -c "oc get project | awk '{print $1}' | sed 's/\(openshift\s*\|openshift-infra\s*\|management-infra\s*\|logging\s*\|default\s*\|kube-system\s*\|testing\s*\|is-test\s*\|NAME\)//g' | sed '/^$/d;s/[[:blank:]]//g'"
      register: myoutput

    - name: Test message
      debug:
        msg: "{{myoutput}}"

    - name: Iterate for project (replace name later)
      include: "./tasks/oc_backup.yml"
      with_items: "{{ myoutput.stdout_lines }}"
