---
- hosts: master1.levvel.internal
  vars_prompt:
    - name: "oc_hostname"
      prompt: "Enter your OC hostname:"
    - name: "oc_user"
      prompt: "Username:"
    - name: "oc_password"
      prompt: "Password:"

  tasks:
    - name: Login to OpenShift
      command: bash -c "oc login {{oc_hostname}} -u {{oc_user}} -p {{oc_password}}"

    - name: Get the Project names
      command: bash -c "oc get project | awk '{print $1}' | sed 's/\(openshift\s*\|openshift-infra\s*\|management-infra\s*\|logging\s*\|default\s*\|kube-system\s*\|testing\s*\|is-test\s*\|NAME\)//g' | sed '/^$/d;s/[[:blank:]]//g'"
      register: myoutput

    - name: Test message
      debug:
        msg: "{{myoutput}}"

    - name: Back up API objects at the project level
      include: "./tasks/oc_backup.yml"
      with_items: "{{ myoutput.stdout_lines }}"
    
    - name: Creating a .tar file of backup folder
      command: bash -c "tar -zcvf /tmp/project_backups_{{ansible_date_time.date}}_{{1000 | random }}.tar.gz project_backups --owner=ec2-user --group=ec2-user"  
        
