---
- name: Echo item name {{ item }}
  debug:
    msg: "{{ item }}"

- file:
    state: directory
    path: "/home/ec2-user/project_backups/{{ item }}"
    owner: ec2-user
    mode: "0744"

- name: Change project
  shell: oc project {{ item }}
  args:
    chdir: "/home/ec2-user/project_backups/{{ item }}"

- name: Backup Image-streams
  shell: oc get is -o yaml > {{ item }}-is.yaml
  args:
    chdir: "/home/ec2-user/project_backups/{{ item }}"

- name: Backup Secrets
  shell: oc get secrets -o yaml > {{ item }}-secrets.yaml
  args:
    chdir: "/home/ec2-user/project_backups/{{ item }}"

- name: Backup Serviceaccounts
  shell: oc get serviceaccount -o yaml > {{ item }}-serviceaccounts.yaml
  args:
    chdir: "/home/ec2-user/project_backups/{{ item }}"

- name: Backup Role-bindings
  shell: oc get rolebindings -o yaml > {{ item }}-rolebindings.yaml
  args:
    chdir: "/home/ec2-user/project_backups/{{ item }}"

- name: Backup Config-maps
  shell: oc get configmaps -o yaml > {{ item }}-configmaps.yaml
  args:
    chdir: "/home/ec2-user/project_backups/{{ item }}"

- name: Backup Deployment configs
  shell: oc get dc -o yaml > {{ item }}-dc.yaml
  args:
    chdir: "/home/ec2-user/project_backups/{{ item }}"

- name: Backup Persistent voulme claims
  shell: oc get pvc -o yaml > {{ item }}-pvc.yaml
  args:
    chdir: "/home/ec2-user/project_backups/{{ item }}"

- name: Backup Build configs
  shell: oc get bc -o yaml > {{ item }}-bc.yaml
  args:
    chdir: "/home/ec2-user/project_backups/{{ item }}"

- name: Backup Services
  shell: oc get services -o yaml > {{ item }}-services.yaml
  args:
    chdir: "/home/ec2-user/project_backups/{{ item }}"

- name: Backup Routes
  shell: oc get routes -o yaml > {{ item }}-routes.yaml
  args:
    chdir: "/home/ec2-user/project_backups/{{ item }}"

- file: 
    state: directory
    recurse: yes
    path: /home/ec2-user/project_backups
    owner: ec2-user
    group: ec2-user
    mode: "0764"
